apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vprodb-pvc
  labels:
    app: vprodb
spec:
  storageClassName: Default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
