apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  db-pass: dnByb2RicGFzcw==
  # base64 encoded value of 'password123'
  rmq-pass: Z3Vlc3Q=
 # base64 encoded value of 'rmq-pass123'
  